version: '3.8'

services:
  ventaasistidafront:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ventaasistidafront
    restart: always
    ports:
      - "3000:3000"
    networks: 
      - ventaasistida
    env_file:
      - .env.development
networks:
  ventaasistida:
    external: true
