import '@/styles/globals.css'
import { Roboto, Sanchez } from 'next/font/google'
import { Providers } from '@/redux/provider'

const roboto = Roboto({
  weight: ['100', '300', '400', '500', '700', '900'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-roboto',
})

const sanchez = Sanchez({
  weight: ['400'],
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-sanchez',
})


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${roboto.variable} ${sanchez.variable} font-roboto`}>
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
